blueprint:
  name: Doorbell Gemini Notification
  description: |
    Sends a rich notification with the Gemini-generated description and image.
    Designed to be called by other automations, passing 'description' and 'image_path' variables.
  domain: script
  author: Hammad Arif
  input:
    title:
      name: Notification Title
      description: Title of the notification.
      default: "Doorbell Camera Event"
      selector:
        text:

    notify_service:
      name: Notification Service
      description: Choose a notify.* service like `notify.mobile_app_your_device`.
      selector:
        text:

variables:
  image_url: "{{ image_path | replace('/config/www', '/local') }}"

sequence:
  - service: !input notify_service
    data:
      title: !input title
      message: "{{ description }}"
      data:
        image: "{{ image_url }}"
