blueprint:
  name: Doorbell Gemini Notification
  description: |
    Sends a rich notification with the Gemini-generated description and image.
    Designed to be called by other automations, passing 'description' and 'image_path' variables.
  domain: script
  author: Hammad Arif
  input:
    target_device:
      name: Mobile App Device
      description: Select the mobile app device to send notifications to (e.g., your phone).
      selector:
        device:
          integration: mobile_app 

    notification_title:
      name: Notification Title
      description: Title of the notification.
      default: "Doorbell Camera Event"
      selector:
        text:

variables:
  image_url: "{{ image_path | replace('/config/www', '/local') }}"

sequence:
  - service: mobile_app.notify 
    data:
      title: !input notification_title
      message: "{{ description }}" 
      data:
        image: "{{ image_url }}"
    target: 
      device_id: !input target_device